apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongo-depl
spec:
  replicas: 1
  selector:
  # how deployment going to find the pod that it actually creates
    matchLabels:
      app: auth-mongo
  template:
    metadata:
    # label that apply the pod
      labels:
        app: auth-mongo 
    spec:
      containers:
        - name: auth-mongo 
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-srv
spec:
# is telling the service which pods it is going to govern access to.
  selector:
    app: auth-mongo
  ports: 
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017